[project]
name = "multiagent-rag-app"
version = "0.1.0"
description = ""
authors = [
    {name = "Yonty", email = "117046900+Jonathan-Poran@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11"
# Dependencies are managed via requirements.txt
